name: 'Setup StackQL'

on:
  push:
    branches:
    - main
    - 'develop-**'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  stackql-test-matrix:
    name: Stackql local run on ${{ matrix.os }} ${{ matrix.use_wrapper && 'with' || 'without'  }} wrapper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        use_wrapper: [true, false]

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.4

    - name: Setup Stackql
      uses: ./
      with:
        use_wrapper: ${{matrix.use_wrapper}}

    - name: Validate Stackql Version
      run: |
        stackql --version

    - name: Use GitHub Provider
      run: |
        stackql exec -i ./examples/github-example.iql
      env: 
        STACKQL_GITHUB_USERNAME: ${{  secrets.STACKQL_GITHUB_USERNAME }}
        STACKQL_GITHUB_PASSWORD: ${{  secrets.STACKQL_GITHUB_PASSWORD }}
  
    - name: Use Google Provider
      run: | 
        stackql exec -i ./examples/google-example.iql
      env: 
        GOOGLE_CREDENTIALS : ${{  secrets.GOOGLE_CREDENTIALS  }}

    - name: Handle error
      if: ${{ matrix.use_wrapper}}
      continue-on-error: true
      run: | ## specify a query file that doesnt exist
        stackql exec -i ./examples/does-not-exist.iql
